openapi: 3.0.0

info:
  title: USER SAMPLE API
  version: 1.0.0
  description: API for managing Users
  contact:
    name: Huntercodexs API team
    email: support@huntercodexs.com

servers:
  - url: http://localhost:8080/huntercodexs/api/v1/management
    description: STG
  - url: http://localhost:8080/huntercodexs/api/v1/management
    description: QA
  - url: http://localhost:8080/huntercodexs/api/v1/management
    description: UAT
  - url: http://localhost:8080/huntercodexs/api/v1/management
    description: PROD

paths:
  /users:
    post:
      tags:
        - Users Management
      summary: Create a new User
      operationId: createNewUser
      description: |
        ## Responsibilities
        * Creates a new User entity in the system.

        ---
        
        ## Requirements
        * To access this endpoint, the client must have one of the following role sets:
          * `ADMIN` and `USER` and `AUTH-BASIC`

      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        '201':
          description: User successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateUserResponse'

        '400':
          description: |
            Bad Request
            
            This endpoint can throw the following errors:
            
            ```
            [{"code": "400", "message": "Username is required."}]
            ```

          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'

        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
        '422':
          description: |
            Unprocessable Entity
            
            This endpoint can throw the following errors:
            
            ```
            [{ "code": "422001", "message": "The user already exists." }]
            ```

          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
        '500':
          description: |
            Internal Server Error
            
            This endpoint can throw the following errors:

            ```
            [{ "code": "500001", "message": "Failed to integrate with User Data Sample API." }]
            ```

          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
        'default':
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
    get:
      tags:
        - Users Management
      summary: List all Users
      operationId: getAllUsers
      description: |
        ## Responsibilities
        * Retrieves a paginated list of all Users available to the authenticated admin user.
        * Supports filtering and pagination to optimize performance and usability.

        ---
        
        ## Requirements
        * To access this endpoint, the client must have one of the following role sets:
          * `ADMIN` and `USER` and `AUTH-BASIC`

      security:
        - bearerAuth: []
      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 20
          description: Maximum number of items to return
        - name: offset
          in: query
          required: false
          schema:
            type: integer
            default: 0
          description: Starting index for pagination
        - name: name
          in: query
          required: false
          schema:
            type: string
          description: Filter by User name
      responses:
        '200':
          description: Users retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsersResponsePagination'
        "206":
          description: Partial Content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsersResponsePagination'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
        'default':
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
  /users/{userId}:
    get:
      tags:
        - Users Management
      summary: Get details of a User by Id
      operationId: getUserById
      description: |
        ## Responsibilities
        * Retrieves a unique User by Id available to the authenticated admin user.

        ---
        
        ## Requirements
        * To access this endpoint, the client must have one of the following role sets:
          * `ADMIN` and `USER` and `AUTH-BASIC`

      security:
        - bearerAuth: []
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
          description: User Id
      responses:
        '200':
          description: User details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
        '404':
          description: |
            Not Found
            
            This endpoint can throw the following errors:
            
            ```
            [{"code": "404001", "message": "User not found."}]
            ```
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
        'default':
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
    delete:
      x-rate-limit-enabled: true
      tags:
        - Users Management
      summary: Delete a User by Id
      operationId: deleteUserById
      description: |
        ## Responsibilities
        * Delete a unique User by Id available to the authenticated admin user.

        ---
        
        ## Requirements
        * To access this endpoint, the client must have one of the following role sets:
          * `ADMIN` and `USER` and `AUTH-BASIC`

      security:
        - bearerAuth: []
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
          description: User Id
      responses:
        '204':
          description: User deleted successfully
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
        '404':
          description: |
            Not Found
            
            This endpoint can throw the following errors:
            
            ```
            [{"code": "404001", "message": "User not found."}]
            ```
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
        'default':
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
    patch:
      tags:
        - Users Management
      summary: Update partial data of User by Id
      operationId: patchUserById
      description: |
        ## Responsibilities
        * Update a partial data of a unique User by Id available to the authenticated admin user.

        ---
        
        ## Requirements
        * To access this endpoint, the client must have one of the following role sets:
          * `ADMIN` and `USER` and `AUTH-BASIC`

      security:
        - bearerAuth: []
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
          description: User Id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpdateRequest'
      responses:
        '204':
          description: No content
        '400':
          description: |
            Bad Request
            
            This endpoint can throw the following errors:
            
            ```
            [{"code": "400", "message": "Bad Request"}]
            [{"code": "400001", "message": "At least one attribute is required to perform the update."}]
            ```
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
        '404':
          description: |
            Not Found
            
            This endpoint can throw the following errors:
            
            ```
            [{"code": "404001", "message": "User not found."}]
            ```
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
        '422':
          description: |
            Unprocessable Entity
            
            This endpoint can throw the following errors:
            
            ```
            [{ "code": "422001", "message": "The name already exists." }]
            ```
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
        'default':
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'

components:
  schemas:
    CreateUserRequest:
      type: object
      required:
        - name
        - email
      properties:
        name:
          type: string
          example: Username
          minLength: 3
        email:
          type: string
          example: user@email.com

    CreateUserResponse:
      type: object
      properties:
        id:
          type: string
          example: '5a2d6db58b9a2900088237f1'

    UsersResponsePagination:
      required:
        - users
        - pagination
      type: object
      properties:
        users:
          type: array
          items:
            $ref: '#/components/schemas/UserResponse'
        pagination:
          $ref: '#/components/schemas/Pagination'

    UserResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
          x-field-extra-annotation: '@JsonInclude(JsonInclude.Include.NON_NULL)'
          #x-field-extra-annotation: '@JsonProperty("id")'
        createdAt:
          type: string

    UserUpdateRequest:
      type: object
      properties:
        name:
          type: string
          example: Updated User name
        email:
          type: string
          example: Updated User email

    ErrorModel:
      type: array
      items:
        type: object
        required:
          - code
          - message
        properties:
          code:
            type: string
            example: "code"
          message:
            type: string
            example: "message"

    Pagination:
      type: object
      properties:
        offset:
          type: number
        limit:
          type: number
        totalCount:
          type: number
        totalPages:
          type: number
        links:
          type: array
          description: Links for next page, previous page, first page and last page
          items:
            $ref: '#/components/schemas/PaginationLink'

    PaginationLink:
      required:
        - href
        - rel
      type: object
      properties:
        href:
          type: string
          example: 'http://localhost:8080/pagination-sample/v1/resource?limit=1&offset=0'
        rel:
          type: string
          description: Expected values are **Last**, **Previous**, **Next** or **First**

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
