# ----------------------------------------------------------
# APP INFO CONFIGURATIONS
info.app.name=@project.artifactId@
info.app.description=Library to help developers make integration easily
info.app.version=@project.version@
spring.application.name=huntercodexs.integration

# ----------------------------------------------------------
# LOG CONFIG
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=INFO
logging.level.org.springframework.security.oauth2=INFO

# ----------------------------------------------------------
# JACKSON CONFIGURATIONS
spring.jackson.default-property-inclusion=non_null
spring.jackson.deserialization.fail-on-missing-creator-properties=true
spring.jackson.deserialization.fail-on-unknown-properties=false
spring.jackson.mapper.accept-case-insensitive-properties=false
spring.jackson.serialization.write-date-keys-as-timestamps=false
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.serialization.write-empty-json-arrays=true

# ----------------------------------------------------------
# EXPOSE ACTUATOR ENDPOINTS
management.endpoints.web.exposure.include=health,info,metrics,prometheus,circuitbreakers
management.endpoint.health.show-details=ALWAYS
management.health.circuitbreakers.enabled=true
management.tracing.enabled=true

# ----------------------------------------------------------
# FEIGN CONFIG
huntercodexs.integration.client.config.logging.enabled=true
huntercodexs.integration.client.config.retryer.period=3000
huntercodexs.integration.client.config.retryer.max-period=10000
huntercodexs.integration.client.config.retryer.max-attempts=3
huntercodexs.integration.client.config.proxy.enable=false
huntercodexs.integration.client.config.proxy.host=localhost
huntercodexs.integration.client.config.proxy.port=8080

# ----------------------------------------------------------
# CIRCUIT BREAKER DEFAULT CONFIG
resilience4j.circuitbreaker.configs.default.failureRateThreshold=70
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=600000
resilience4j.circuitbreaker.configs.default.slowCallDurationThreshold=6000
resilience4j.circuitbreaker.configs.default.slidingWindowType=TIME_BASED
resilience4j.circuitbreaker.configs.default.minimumNumberOfCalls=10
resilience4j.circuitbreaker.configs.default.slowCallRateThreshold=70
resilience4j.circuitbreaker.configs.default.ignoreExceptions=
resilience4j.circuitbreaker.configs.default.slidingWindowSize=60
resilience4j.circuitbreaker.configs.default.registerHealthIndicator=true

# ----------------------------------------------------------
# REDIS
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=
spring.data.redis.timeout=1000
spring.data.redis.ssl.enabled=true
# REDIS LOG CONFIGURATIONS
huntercodexs.integration.redis.enabled=true
huntercodexs.integration.redis.log.enabled=true

# ----------------------------------------------------------
# MONGODB
spring.data.mongodb.uri=mongodb://localhost:27017
spring.data.mongodb.database=test
# MONGODB RETRY CONFIGURATIONS
huntercodexs.integration.mongodb.retry.enabled=true
huntercodexs.integration.mongodb.retry.maxAttempts=3
huntercodexs.integration.mongodb.retry.initialInterval=100
huntercodexs.integration.mongodb.retry.maxInterval=1000
huntercodexs.integration.mongodb.retry.multiplier=2.0
# MONGODB LOG CONFIGURATIONS
logging.level.org.mongodb.driver=ERROR
logging.level.org.mongodb.driver.cluster=ERROR

# ----------------------------------------------------------
# RATE LIMIT CONFIGURATIONS
huntercodexs.integration.rate-limit.enabled=true
huntercodexs.integration.rate-limit.limit=10
huntercodexs.integration.rate-limit.duration=1
# Use: seconds, minutes, hours
huntercodexs.integration.rate-limit.unit=seconds
huntercodexs.integration.rate-limit.cache-prefix=ratelimit-prefix-default

# ----------------------------------------------------------
# RATE LIMIT SERVICE BUS CONFIGURATIONS
huntercodexs.integration.rate-limit-service-bus.enabled=true
huntercodexs.integration.rate-limit-service-bus.log.enabled=true
huntercodexs.integration.rate-limit-service-bus.limit=10
huntercodexs.integration.rate-limit-service-bus.duration=1
# Use: seconds, minutes, hours
huntercodexs.integration.rate-limit-service-bus.unit=seconds
huntercodexs.integration.rate-limit-service-bus.cache-prefix=ratelimit-service-bus-prefix-default
huntercodexs.integration.rate-limit-service-bus.key-parameter=__DEFAULT__

# ----------------------------------------------------------
# KAFKA PRODUCER CONFIGURATIONS
huntercodexs.integration.kafka.producer.enabled=true
spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.cluster-key=kafka
spring.kafka.producer.cluster-password=admin_secret
spring.kafka.producer.cluster-topic-name=
# Use: PLAINTEXT, SASL_PLAINTEXT, SASL_SSL
spring.kafka.producer.security.protocol=SASL_SSL
spring.kafka.producer.sasl.mechanism=PLAIN
spring.kafka.producer.ssl.truststore.location=./src/main/resources/certs/broker.truststore.jks
spring.kafka.producer.ssl.truststore.password=changeit
spring.kafka.producer.ssl.key-password=changeit
spring.kafka.producer.ssl.disable-hostname-verification=true
spring.kafka.producer.client-requires-trust-key=false

# KAFKA CONSUMER CONFIGURATIONS
huntercodexs.integration.kafka.consumer.enabled=true
spring.kafka.consumer.bootstrap-servers=localhost:9092
spring.kafka.consumer.cluster-key=kafka
spring.kafka.consumer.cluster-password=admin_secret
spring.kafka.consumer.cluster-topic-name=
# Use: PLAINTEXT, SASL_PLAINTEXT, SASL_SSL
spring.kafka.consumer.security.protocol=SASL_SSL
spring.kafka.consumer.sasl.mechanism=PLAIN
spring.kafka.consumer.ssl.truststore.location=./src/main/resources/certs/broker.truststore.jks
spring.kafka.consumer.ssl.truststore.password=changeit
spring.kafka.consumer.ssl.key-password=changeit
spring.kafka.consumer.ssl.disable-hostname-verification=true
spring.kafka.consumer.client-requires-trust-key=false
spring.kafka.consumer.group-id=
spring.kafka.consumer.max-poll-interval-ms=600000
spring.kafka.consumer.max-poll-records=120
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.message-discard=false
spring.kafka.consumer.ack-mode=MANUAL

# ----------------------------------------------------------
# SERVICES BUS CONFIGURATIONS
spring.cloud.azure.servicebus.connection-string=Endpoint=sb://${YOUR_SERVICEBUS_NAMESPACE}.servicebus.windows.net/;SharedAccessKeyName=${YOUR_KEY_NAME};SharedAccessKey=${YOUR_ACCESS_KEY}
# SERVICE BUS CONSUMER CONFIGURATIONS (SINGLE OR LIST)
spring.cloud.azure.servicebus.consumer.single.enabled=true
spring.cloud.azure.servicebus.consumer.target-queue-name=${YOUR_SINGLE_CONSUMER_QUEUE_NAME}
#spring.cloud.azure.servicebus.consumer.list.enabled=true
#spring.cloud.azure.servicebus.consumer.target-queue-list=${YOUR_LIST_CONSUMER_QUEUE_NAME}
spring.cloud.azure.servicebus.consumer.entity-type=queue
spring.cloud.azure.servicebus.consumer.receive-mode=PEEK_LOCK
spring.cloud.azure.servicebus.consumer.prefetch-count=1
spring.cloud.azure.servicebus.consumer.max-concurrent-calls=1
spring.cloud.azure.servicebus.consumer.max-auto-renew-duration-minutes=5
spring.cloud.azure.servicebus.consumer.disable-auto-complete=true
# SERVICE BUS PRODUCER CONFIGURATIONS
spring.cloud.azure.servicebus.producer.enabled=true
spring.cloud.azure.servicebus.producer.target-queue-name=${YOUR_PRODUCER_QUEUE_NAME}
spring.cloud.azure.servicebus.producer.entity-type=queue
spring.cloud.azure.servicebus.producer.receive-mode=PEEK_LOCK
spring.cloud.azure.servicebus.producer.delay-minutes=1
spring.cloud.azure.servicebus.producer.delay-seconds=1

# ----------------------------------------------------------
# RABBITMQ CONFIGURATIONS

# ==> RABBITMQ CONNECTION CONFIGURATIONS
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
# Needs to create this vhost in the rabbitmq container service:
# rabbitmqctl add_vhost /integration
# rabbitmqctl set_permissions -p /integration guest ".*" ".*" ".*"
#spring.rabbitmq.virtual-host=/integration
spring.rabbitmq.virtual-host=/integrationlist

# RABBITMQ GLOBAL CONFIGURATIONS
huntercodexs.integration.rabbitmq.global.ackMode=MANUAL
huntercodexs.integration.rabbitmq.global.concurrentConsumers=1
huntercodexs.integration.rabbitmq.global.maxConcurrentConsumers=5
huntercodexs.integration.rabbitmq.global.prefetch=10
huntercodexs.integration.rabbitmq.global.initialInterval=1000
huntercodexs.integration.rabbitmq.global.maxInterval=10000
huntercodexs.integration.rabbitmq.global.multiplier=1.5
huntercodexs.integration.rabbitmq.global.maxAttempts=3
huntercodexs.integration.rabbitmq.global.logEnabled=true

# ==> PRODUCER GLOBAL CONFIGURATIONS
#huntercodexs.integration.rabbitmq.producers.name=ORDER_CREATED
#huntercodexs.integration.rabbitmq.producers.exchange=order.exchange
#huntercodexs.integration.rabbitmq.producers.routingKey=order.created
#huntercodexs.integration.rabbitmq.producers.deliveryMode=PERSISTENT
#huntercodexs.integration.rabbitmq.producers.exchangeType=direct
#huntercodexs.integration.rabbitmq.producers.retryEnabled=true
#huntercodexs.integration.rabbitmq.producers.retryTtlMilliseconds=5000
#huntercodexs.integration.rabbitmq.producers.maxRetries=3
#huntercodexs.integration.rabbitmq.producers.dlqEnabled=true
#huntercodexs.integration.rabbitmq.producers.logEnabled=true

# ==> CONSUMER GLOBAL CONFIGURATIONS
#huntercodexs.integration.rabbitmq.consumers.name=ORDER_CREATED
#huntercodexs.integration.rabbitmq.consumers.exchange=order.exchange
#huntercodexs.integration.rabbitmq.consumers.routingKey=order.created
#huntercodexs.integration.rabbitmq.consumers.queue=order.created.queue
#huntercodexs.integration.rabbitmq.consumers.exchangeType=direct
#huntercodexs.integration.rabbitmq.consumers.retryEnabled=true
#huntercodexs.integration.rabbitmq.consumers.retryTtlMilliseconds=5000
#huntercodexs.integration.rabbitmq.consumers.maxRetries=3
#huntercodexs.integration.rabbitmq.consumers.dlqEnabled=true
#huntercodexs.integration.rabbitmq.consumers.logEnabled=true

# RABBITMQ CUSTOM CONFIGURATIONS

# ==> PRODUCERS 1 CONFIG (list)
huntercodexs.integration.rabbitmq.producers[0].logEnabled=true
huntercodexs.integration.rabbitmq.producers[0].name=ORDER_CREATED
huntercodexs.integration.rabbitmq.producers[0].exchange=order.exchange
huntercodexs.integration.rabbitmq.producers[0].routingKey=order.created
huntercodexs.integration.rabbitmq.producers[0].deliveryMode=PERSISTENT
huntercodexs.integration.rabbitmq.producers[0].exchangeType=direct
huntercodexs.integration.rabbitmq.producers[0].retryEnabled=true
huntercodexs.integration.rabbitmq.producers[0].retryTtlMilliseconds=5000
huntercodexs.integration.rabbitmq.producers[0].maxRetries=3
huntercodexs.integration.rabbitmq.producers[0].dlqEnabled=true
# ==> PRODUCERS 2 CONFIG (list)
huntercodexs.integration.rabbitmq.producers[1].logEnabled=true
huntercodexs.integration.rabbitmq.producers[1].name=USER_REGISTERED
huntercodexs.integration.rabbitmq.producers[1].exchange=user.exchange
huntercodexs.integration.rabbitmq.producers[1].routingKey=user.registered
huntercodexs.integration.rabbitmq.producers[1].exchangeType=topic
huntercodexs.integration.rabbitmq.producers[1].retryEnabled=true
huntercodexs.integration.rabbitmq.producers[1].retryTtlMilliseconds=3000
huntercodexs.integration.rabbitmq.producers[1].maxRetries=3
huntercodexs.integration.rabbitmq.producers[1].dlqEnabled=true

# ==> CONSUMERS 1 CONFIG (list)
huntercodexs.integration.rabbitmq.consumers[0].logEnabled=true
huntercodexs.integration.rabbitmq.consumers[0].name=ORDER_CREATED
huntercodexs.integration.rabbitmq.consumers[0].exchange=order.exchange
huntercodexs.integration.rabbitmq.consumers[0].queue=order.created.queue
huntercodexs.integration.rabbitmq.consumers[0].routingKey=order.created
huntercodexs.integration.rabbitmq.consumers[0].exchangeType=direct
huntercodexs.integration.rabbitmq.consumers[0].retryEnabled=true
huntercodexs.integration.rabbitmq.consumers[0].retryTtlMilliseconds=5000
huntercodexs.integration.rabbitmq.consumers[0].maxRetries=3
huntercodexs.integration.rabbitmq.consumers[0].dlqEnabled=true
# ==> CONSUMERS 2 CONFIG (list)
huntercodexs.integration.rabbitmq.consumers[1].logEnabled=true
huntercodexs.integration.rabbitmq.consumers[1].name=USER_REGISTERED
huntercodexs.integration.rabbitmq.consumers[1].exchange=user.exchange
huntercodexs.integration.rabbitmq.consumers[1].queue=user.registered.queue
huntercodexs.integration.rabbitmq.consumers[1].routingKey=user.registered
huntercodexs.integration.rabbitmq.consumers[1].exchangeType=topic
huntercodexs.integration.rabbitmq.consumers[1].retryEnabled=true
huntercodexs.integration.rabbitmq.consumers[1].retryTtlMilliseconds=3000
huntercodexs.integration.rabbitmq.consumers[1].maxRetries=3
huntercodexs.integration.rabbitmq.consumers[1].dlqEnabled=true

# ----------------------------------------------------------
# SQS CONFIGURATIONS

huntercodexs.integration.sqs.enabled=true
cloud.aws.account-id=${accountidaws}
cloud.aws.queue.name=sqs-queue-test1,sqs-queue-test2
cloud.aws.stack.auto=false
cloud.aws.region.static=us-east-1
cloud.aws.credentials.accessKey=${accesskeyaws}
cloud.aws.credentials.secretKey=${secretkeyaws}
#cloud.aws.endpoint.uri=https://localhost.localstack.cloud:4566/
cloud.aws.endpoint.uri=${urlqueueaws}

# ----------------------------------------------------------
# TESTS CONFIG
spring.test.parallel.enabled=false
junit.jupiter.execution.parallel.enabled=true

